#!/usr/bin/python3 -u
"""pvefw-neo launcher.

Note: -u disables stdout/stderr buffering so daemon log shows immediately.
"""

import os
import sys

# Add the repo root to sys.path so 'pvefw_neo_src' is importable as a package
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from pvefw_neo_src.main import main
main()
